env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

parser: '@typescript-eslint/parser'

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
