export enum ActionType {
  GET_ACTIVE_OFFER_ID = `GET_ACTIVE_OFFER_ID`,
  GET_ALL_OFFERS = `GET_ALL_OFFERS`,
  GET_AUTH_STATUS = `GET_AUTH_STATUS`,
  GET_CURRENT_FILTERING = `GET_CURRENT_FILTERING`,
  GET_CURRENT_SORTING = `GET_CURRENT_SORTING`,
  GET_FAVORITE_OFFERS = `GET_FAVORITE_OFFERS`,
  GET_NEARBY_OFFERS = `GET_NEARBY_OFFERS`,
  GET_SINGLE_OFFER = `GET_SINGLE_OFFER`,
  GET_SINGLE_OFFER_REVIEWS = `GET_SINGLE_OFFER_REVIEWS`,
  GET_USER_DATA = `GET_USER_DATA`,
  REDIRECT_TO_ROUTE = `REDIRECT_TO_ROUTE`,
  SET_IS_DATA_SENDING = `SET_IS_DATA_SENDING`,
  SET_IS_SENDING_ERROR = `SET_IS_SENDING_ERROR`,
  UPDATE_OFFERS = `UPDATE_OFFERS`
}
