export enum ActionType {
  GET_ACTIVE_OFFER_ID = `GET_ACTIVE_OFFER_ID`,
  GET_CURRENT_FILTERING = `GET_CURRENT_FILTERING`,
  GET_CURRENT_SORTING = `GET_CURRENT_SORTING`,
  GET_OFFERS = `GET_OFFERS`
}
