export enum ActionType {
  GET_ACTIVE_OFFER_ID = `GET_ACTIVE_OFFER_ID`,
  GET_ALL_OFFERS = `GET_ALL_OFFERS`,
  GET_AUTH_STATUS = `GET_AUTH_STATUS`,
  GET_CURRENT_FILTERING = `GET_CURRENT_FILTERING`,
  GET_CURRENT_SORTING = `GET_CURRENT_SORTING`,
  GET_FAVORITE_OFFERS = `GET_FAVORITE_OFFERS`
}
