export const SHAKE_DURATION = 750;

export enum ActionType {
  SET_ACTIVE_OFFER_ID = `SET_ACTIVE_OFFER_ID`,
  SET_ALL_OFFERS = `SET_ALL_OFFERS`,
  SET_AUTH_STATUS = `SET_AUTH_STATUS`,
  SET_CURRENT_CITY = `SET_CURRENT_CITY`,
  SET_CURRENT_SORTING = `SET_CURRENT_SORTING`,
  SET_FAVORITE_OFFERS = `SET_FAVORITE_OFFERS`,
  SET_FAVORITES_IS_LOADING = `SET_FAVORITES_IS_LOADING`,
  SET_FAVORITES_LOADING_ERROR = `SET_FAVORITES_LOADING_ERROR`,
  SET_LOGIN_IS_SENDING = `SET_LOGIN_IS_SENDING`,
  SET_LOGIN_SENDING_ERROR = `SET_LOGIN_SENDING_ERROR`,
  SET_MAIN_IS_LOADING = `SET_MAIN_IS_LOADING`,
  SET_MAIN_LOADING_ERROR = `SET_MAIN_LOADING_ERROR`,
  SET_NEARBY_OFFERS = `SET_NEARBY_OFFERS`,
  SET_OFFER = `SET_OFFER`,
  SET_OFFER_FAVORITE_STATUS = `SET_OFFER_FAVORITE_STATUS`,
  SET_PROPERTY_IS_LOADING = `SET_PROPERTY_IS_LOADING`,
  SET_PROPERTY_LOADING_ERROR = `SET_PROPERTY_LOADING_ERROR`,
  SET_REDIRECT_TO_ROUTE = `SET_REDIRECT_TO_ROUTE`,
  SET_REVIEW_IS_SENDING = `SET_REVIEW_IS_SENDING`,
  SET_REVIEW_SENDING_ERROR = `SET_REVIEW_SENDING_ERROR`,
  SET_REVIEWS = `SET_REVIEWS`,
  SET_USER = `SET_USER`
}

export enum APIEndpoint {
  HOTELS = `/hotels/`,
  NEARBY = `/nearby/`,
  FAVORITE = `/favorite/`,
  COMMENTS = `/comments/`,
  LOGIN = `/login/`,
  LOGOUT = `/logout/`
}

export enum AttributeName {
  DISABLED = `disabled`,
  FILL = `fill`,
  STROKE = `stroke`
}

export enum AttributeValue{
  EMPTY = ``,
  RED = `#ff0000`
}

