export enum ActionType {
  CHANGE_ACTIVE_OFFER_ID = `CHANGE_ACTIVE_OFFER_ID`,
  CHANGE_CURRENT_CITY = `CHANGE_CURRENT_CITY`,
  CHANGE_CURRENT_SORTING = `CHANGE_CURRENT_SORTING`,
  CHANGE_OFFER_FAVORITE_STATUS = `CHANGE_OFFER_FAVORITE_STATUS`,
  GET_ALL_OFFERS = `GET_ALL_OFFERS`,
  GET_FAVORITE_OFFERS = `GET_FAVORITE_OFFERS`,
  GET_NEARBY_OFFERS = `GET_NEARBY_OFFERS`,
  GET_SINGLE_OFFER = `GET_SINGLE_OFFER`,
  GET_REVIEWS = `GET_REVIEWS`,
  GET_USER = `GET_USER`,
  REDIRECT_TO_ROUTE = `REDIRECT_TO_ROUTE`,
  SET_AUTH_STATUS = `SET_AUTH_STATUS`,
  SET_INITIAL_STATE = `SET_INITIAL_STATE`,
  SET_IS_ALL_OFFERS_LOADING = `SET_IS_ALL_OFFERS_LOADING`,
  SET_IS_ALL_OFFERS_LOADING_ERROR = `SET_IS_ALL_OFFERS_LOADING_ERROR`,
  SET_IS_FAVORITE_OFFERS_LOADING = `SET_IS_FAVORITE_OFFERS_LOADING`,
  SET_IS_FAVORITE_OFFERS_LOADING_ERROR = `SET_IS_FAVORITE_OFFERS_LOADING_ERROR`,
  SET_IS_FAVORITE_SENDING = `SET_IS_FAVORITE_SENDING`,
  SET_IS_FAVORITE_SENDING_ERROR = `SET_IS_FAVORITE_SENDING_ERROR`,
  SET_IS_LOGIN_SENDING = `SET_IS_LOGIN_SENDING`,
  SET_IS_LOGIN_SENDING_ERROR = `SET_IS_LOGIN_SENDING_ERROR`,
  SET_IS_REVIEW_SENDING = `SET_IS_REVIEW_SENDING`,
  SET_IS_REVIEW_SENDING_ERROR = `SET_IS_REVIEW_SENDING_ERROR`,
  SET_IS_SINGLE_OFFER_LOADING = `SET_IS_SINGLE_OFFER_LOADING`,
  SET_IS_SINGLE_OFFER_LOADING_ERROR = `SET_IS_SINGLE_OFFER_LOADING_ERROR`
}

export enum APIEndpoint {
  HOTELS = `/hotels/`,
  NEARBY = `/nearby/`,
  FAVORITE = `/favorite/`,
  COMMENTS = `/comments/`,
  LOGIN = `/login/`,
  LOGOUT = `/logout/`
}
